# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    default_filter_set_settings:
        format: webp
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        doctor_achievment:
            filters:
                thumbnail: { size: [74, 73], mode: outbound }
