version: "3"
services:
  proxy:
    restart: always
    image: "nginx"
    ports:
      - "80:80"
    expose:
      - 80
      - 443
    environment:
      VIRTUAL_HOST: "api.tools.trinet.ru"
      LETSENCRYPT_HOST: "api.tools.trinet.ru"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/localhost.crt:/var/www/certs/localhost.crt
      - ./docker/localhost.key:/var/www/certs/localhost.key
    depends_on:
      - web
  web:
    restart: always
    image: "pradex78/php:8"
    volumes:
      - ./:/var/www/html/
      - ./docker/php.ini:/usr/local/etc/php/conf.d/99-docker.ini
      - ./docker/apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/xdebug:/var/xdebug/
    depends_on:
      - db
    expose:
      - 80
  db:
    restart: always
    image: "mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: "getRND90"
    volumes:
      - data:/var/lib/mysql/
    ports:
      - "3306:3306"
  es:
    restart: always
    image: elasticsearch:7.14.1
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
      - "xpack.security.enabled=false"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
    ports:
      - 9201:9200
volumes:
  data:
    external: false
#networks:
#  default:
#    external:
#      name: network1
