# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    temp_directory: '%kernel.project_dir%/var/temp'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    app.search_index_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments:
            -
                App\Entity\Doctor: '@App\Service\Search\DoctorSearchIndex'
                App\Entity\Service: '@App\Service\Search\ServiceSearchIndex'
                App\Entity\Disease: '@App\Service\Search\DiseaseSearchIndex'

    App\Service\Search\SearchIndex:
        arguments: [ '@app.search_index_locator' ]

    Elasticsearch\ClientBuilder: ~

    Elasticsearch\Client:
        factory: [ '@Elasticsearch\ClientBuilder', fromConfig ]
        arguments: [ {'hosts': ['%env(resolve:ELASTICSEARCH_HOST)%:%env(resolve:ELASTICSEARCH_PORT)%']} ]

    Elastica\Client:
        arguments: [ {'host': '%env(resolve:ELASTICSEARCH_HOST)%', 'port': '%env(resolve:ELASTICSEARCH_PORT)%' } ]

